PNDA-4501: Document Flink related features
pndaproject/pnda-guide pull request #109
Opened 2018-04-24 12:50 UTC by mrunmayeejog

# Problem Statement:
PNDA-4501: Document Flink related features

# Changes: 
Updated document by adding description related to flink features like flink application packaging, interactive coding with flink, UI links etc to relevant sections in existing document.

2018-08-23 10:20 UTC, trsmith2 requested changes

2018-08-23 10:20 UTC, trsmith2 commented on console/README.md
> +Apache Flink comes with an interactive [Scala shell](https://ci.apache.org/projects/flink/flink-docs-release-1.4/dev/scala_shell.html) which can be used in local as well as cluster setup. To use the
Dangling sentence...?

2018-08-23 10:20 UTC, trsmith2 commented on console/applications.md
> +- RUNNING_WITH_ERROS -  Running but one or more vertices in failed state
Typo

2018-08-24 12:32 UTC, mrunmayeejog commented
Changes are done. Please review

2018-08-28 15:15 UTC, merged